version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run lint
workflows:
  version: 2.1
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - develop